name: Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  perl-version:
    name: Fetch available perl versions
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-setup-perl@v1
      - id: set-matrix
        name: Generate matrix for perl versions
        shell: perl {0}
        run: |
          use Actions::Core;
          use JSON::PP;
          use version;
          my $perl_min_version = version->parse("v5.8");
          my @versions = grep { version->parse("v$_") >= $perl_min_version }
                         perl_versions(platform => 'linux');
          my @include = map { +{ os => 'ubuntu-latest', perl => $_ } } @versions;
          push @include, {
            os            => 'ubuntu-latest',
            perl          => '5',
            pureperl      => JSON::PP::true,
            force_cc_fail => JSON::PP::true,
          };
          set_output(matrix_include => \@include);
    outputs:
      matrix_include: ${{ steps.set-matrix.outputs.matrix_include }}

  dist:
    name: Make distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Cache ~/perl5
        uses: actions/cache@v5
        with:
          key: ${{ runner.os }}-dist-locallib
          path: ~/perl5
      - name: Perl version
        run: |
          perl -v
      - name: Install cpanm
        run: |
          curl -L https://cpanmin.us | perl - --sudo App::cpanminus
      - name: Install local::lib
        run: |
          cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
      - name: Install author deps
        shell: bash
        run: |
          eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
          cpanm --notest --with-recommends --with-suggests Test::WriteVariants Config::AutoConf Carp inc::latest
      - name: Make distribution
        shell: bash
        run: |
          eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
          perl Makefile.PL
          make manifest dist DISTVNAME=dist
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: dist
          path: ./dist.tar.gz
  test:
    needs: [dist, perl-version]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        perl: ['5']
        pureperl: [false, true]
        include: ${{ fromJSON(needs.perl-version.outputs.matrix_include) }}
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }} (${{ format('{0}, {1}', fromJSON('["","pureperl"]')[matrix.pureperl], fromJSON('["","force cc failure"]')[matrix.force_cc_fail]) }})

    steps:
      - name: Get dist artifact
        uses: actions/download-artifact@v7
        with:
          name: dist

      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        if: matrix.os != 'windows-latest'
        with:
          perl-version: ${{ matrix.perl }}
      - name: Set up perl (Strawberry)
        uses: shogo82148/actions-setup-perl@v1
        if: matrix.os == 'windows-latest'
        with:
          distribution: 'strawberry'

      - run: perl -V

      - name: Install Perl deps
        run: |
          cpanm --notest --installdeps dist.tar.gz

      - name: Run tests
        run:
          cpanm --verbose --test-only
              ${{ fromJSON('[ "", "--pureperl" ]')[ matrix.pureperl ] }}
              ${{ fromJSON('[ "", "--build-args=\"CC=false\"" ]')[ matrix.force_cc_fail ] }}
              dist.tar.gz
