name: Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  dist:
    name: Make distribution
    runs-on: ubuntu-latest
    container:
      image: perldocker/perl-tester:5.42
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Bootstrap author deps
        run: |
          cpanm --notest --with-recommends --with-suggests \
            inc::latest Capture::Tiny Config::AutoConf Test::WriteVariants
      - name: Make distribution
        run: |
          perl Makefile.PL
          make manifest dist DISTVNAME=dist
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: dist
          path: ./dist.tar.gz

  test-linux:
    name: 'Linux Perl ${{ matrix.perl }}${{ matrix.pureperl && '' (pureperl)'' || '' (default)'' }}${{ matrix.force_cc_fail && '' + force CC fail'' || '' }}'
    needs: dist
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl: ['5.30', '5.32', '5.34', '5.36', '5.38', '5.40', '5.42']
        pureperl: [false, true]
        include:
          - perl: '5.42'
            pureperl: true
            force_cc_fail: true
    container:
      image: perldocker/perl-tester:${{ matrix.perl }}
    steps:
      - name: Get dist artifact
        uses: actions/download-artifact@v7
        with:
          name: dist
      - run: perl -V
      - name: Install Perl deps
        run: cpanm --notest --installdeps dist.tar.gz
      - name: Run tests
        run: |
          cpanm --verbose --test-only \
            ${{ matrix.pureperl && '--pureperl' || '' }} \
            ${{ matrix.force_cc_fail && '--build-args="CC=false"' || '' }} \
            dist.tar.gz

  test-other-os:
    name: 'Perl latest on ${{ matrix.os }}'
    needs: dist
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - name: Get dist artifact
        uses: actions/download-artifact@v7
        with:
          name: dist
      - name: Set up perl
        if: matrix.os != 'windows-latest'
        uses: shogo82148/actions-setup-perl@v1
      - name: Set up perl (Strawberry)
        if: matrix.os == 'windows-latest'
        uses: shogo82148/actions-setup-perl@v1
        with:
          distribution: strawberry
      - run: perl -V
      - name: Install Perl deps
        run: cpanm --notest --installdeps dist.tar.gz
      - name: Run tests
        run: cpanm --verbose --test-only dist.tar.gz
